CREATE TABLE PUBLIC.ORDERS
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CUSTOMER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    AMOUNT INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CUSTOMERS FOREIGN KEY (CUSTOMER_ID)
        REFERENCES PUBLIC.CUSTOMERS (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT BOOK FOREIGN KEY (BOOK_ID)
        REFERENCES PUBLIC.BOOKS (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

ALTER TABLE IF EXISTS PUBLIC.ORDERS
    OWNER TO POSTGRES;
